### ISSUE TITLE
getUserWhere($key, $value) doesn't fetch records in the extended user table

### ISSUE THREAD

**Issue by paynegreen** [DevlessTeam/DV-PHP-CORE#101]

**Comment by paulkarikari** [comment]
@paynegreen Kindly add more description, please. :wink:

**Comment by paynegreen** [comment]
The getUserWhere($key, $value) rule only fetches the records from the users' table and doesn't fetch records from the user_profile (extended) table on the DevLess module.

**Comment by paynegreen** [comment]
Added a method get `getUserUsingExtraParams(["location" => "foo"])` to fetch to retrieve users and extras params.

**Comment by paynegreen** [comment]
Issue fixed.
