### ISSUE TITLE
Database-rec missing

### ISSUE THREAD

**Issue by seanmavley** [DevlessTeam/DV-PHP-CORE#36]
Any chance that database.sqlite3 or the database-rec could be recreated automatically should they not exist on startup or when they're requested or one tries to write to?

**Comment by EDDYMENS** [comment]
Well it should be available together with the setup, but yes making it possible to regenerate will be a good option to have

**Comment by seanmavley** [comment]
I deleted my database.\* files because when I spin up the server and accessed in localhost, it asked for email and password I didn't know. Deleting them meant I could respin everything up. 

Maybe the one bundled with the repo should be empty

**Comment by paynegreen** [comment]
It supposed to be empty. I check and rectify that.

**Comment by seanmavley** [comment]
@paynegreen okay, if it should be empty, then HTML5 is requiring me to fill the blanks.
Any chance the documentations could be made more concise and cover all the flow involved? At this point, onboarding is my greatest hassle, unless you guys want any developer knocking on your doors always for answers.

Apart from you guys, _no one_ and I mean, literally, no one knows how to use your platform, so please explain what you want happen just like you're saying it to a dumb guy who washed on the beach with a laptop in hand.

**Comment by EDDYMENS** [comment]
@seanmavley I understand your pain  perfectly. I would be lying if I  say onboarding is not  a big issue. It's why with the release of v1.0 we have added Heroku deployments and will be adding a bunch of video tutorials over the course of the week to make the communication clearer .Please bear with us as we are working hard to ensure its usability. Also anything you might have in mind that would help would surely be appreciated.
