### ISSUE TITLE
Array to string conversion

### ISSUE THREAD

**Issue by seanmavley** [DevlessTeam/DV-PHP-CORE#37]
Trying to create a table in Devless with this error message. No error message in browser or terminal console

![screenshot from 2016-08-31 17-09-00](https://cloud.githubusercontent.com/assets/5289083/18138740/bdb9956c-6f9d-11e6-99bd-b6714c7367bb.png)

**Comment by EDDYMENS** [comment]
Can you please give more context, maybe the database option your chose and OS, basically a way to replicate the same error?

**Comment by seanmavley** [comment]
Okay, the OS is Ubuntu. I'm using sqlite3 as database. 
I'm following steps here: https://devless.io/#!/tutorial

Successfully created a database following the steps, then went on to create a table. Creating table brings up the error.

**Comment by EDDYMENS** [comment]
Alright will  replicate the error from my end and push a fix if its broken. I am sure the error is with the sqlite option.
