### ISSUE TITLE
Script commands apply to all tables across a service

### ISSUE THREAD

**Issue by johnotu** [DevlessTeam/DV-PHP-CORE#48]
One cannot specify which table a particular script should apply to. Every command gets applied to all tables in that service so long as the field name is a match.

**Comment by EDDYMENS** [comment]
the  `->onTable()`  method has been added to script on commit `39ddbd` 

![ontable](https://cloud.githubusercontent.com/assets/8077713/21896528/9e6c4c0e-d8de-11e6-9eb9-b5e39b5b91c5.png)
