### ISSUE TITLE
Datatable not working with remote tables

### ISSUE THREAD

**Issue by EDDYMENS** [DevlessTeam/DV-PHP-CORE#55]
In case you feel like resolving this, one place you can get started from is the `DatatableController`

**Comment by paynegreen** [comment]
share the error logs pls

**Comment by EDDYMENS** [comment]
So there are no error logs. Only thing is the Data tables cant show the required fields becuase it uses the laravel field search method to check the local db for the fields .

**Comment by paynegreen** [comment]
issue resolved
