### ISSUE TITLE
Composer Install: PHP version requirements

### ISSUE THREAD

**Issue by mturkson23** [DevlessTeam/DV-PHP-CORE#70]
On the first time of running `composer install` in the root directory I get a 
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php ^5.6.0 but your PHP version (7.0.15) does not satisfy that requirement.
```
I am running Ubuntu 16.04 with PHP 7.0.15-0ubuntu0.16.04.4. 

Previously on Composer version 1.2.1 but the same issue persists even after upgrading to version 1.4.1.
I will proceed with more tests and upgrade this issue if and when necessary.

**Comment by mturkson23** [comment]
Running with
```
composer install --ignore-platform-reqs
```
performs package installation successfully without errors.
Db migration works and `./devless serve` serves web application.

IMHO ignoring platform requirements is a dirty work-around not a solution to the problem. 

Does this mean PHP v7.0.15 (or possibly 7.0.*) is not supported?

**Comment by EDDYMENS** [comment]
@mturkson23 We began checking  7.0.* compatibility  ATM the checks is not complete. Some people run DevLess with 7 smoothly with no issues though.

**Comment by EDDYMENS** [comment]
In the case you have any issues with 7.0.* I will be glad if you let me know will help with the compatibility checks.

**Comment by mturkson23** [comment]
Sure thing. I'll let you know.

**Comment by EDDYMENS** [comment]
Thanks !!
