### ISSUE TITLE
How to switch Devless from http to https?

### ISSUE THREAD

**Issue by devstress** [DevlessTeam/DV-PHP-CORE#78]
Hi team, 

I'm hosting Devless on Shared Hosting Siteground. After I convert it to https, all the css resources are broken. How could I config Devless to https?

https://devless.hackathonsaustralia.com
http://devless.hackathonsaustralia.com

**Comment by devstress** [comment]
The actual problem is the url putting number 1 in the front of the css files
For example: Did not parse stylesheet at 'https://devless.hackathonsaustralia.com/1/css/slidebars.css' because non CSS MIME types are not allowed in strict mode.

**Comment by paynegreen** [comment]
It's been fixed. We will notify you when the patch is released. Thanks.
