### ISSUE TITLE
 button "Add Data" doesn't work in Data Table page

### ISSUE THREAD

**Issue by fannur** [DevlessTeam/DV-PHP-CORE#82]
In version 1.3.2, if visit the page Data Table with get parameters (/datatable?service_name=cafe&table_name=category), button "Add Data" doesn't work, because functio init() in datatable.js was not call. Will work if only change service, because init() function in method $("#service").change

**Comment by paynegreen** [comment]
Thanks, @fannur for reporting the issue. It has been fixed now. I will release in the upcoming patch.
