### ISSUE TITLE
Modal not closing after viewing record from data table

### ISSUE THREAD

**Issue by snamoah** [DevlessTeam/DV-PHP-CORE#84]
I've got a list of records in my Data Table and when I try to view one,  a modal opens with the fields to edit, delete, or cancel. It fails however to close when I click the cancel button. I checked my browser console an note this error:
```
TypeError: undefined is not an object (evaluating '$(this).find("button:focus")[0].innerText')
```

NB: This is on Safari browser

**Comment by paynegreen** [comment]
fixed the issue
