### ISSUE TITLE
add support for php7

### ISSUE THREAD

**Issue by mhsenpc** [DevlessTeam/DV-PHP-CORE#85]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php ^5.6.0 but your PHP version (7.1.12) does not satisfy that requirement.

**Comment by EDDYMENS** [comment]
The project is currently well tested with PHP 5.6.0  and so we try to keep it safe by keeping the PHP version to the minimum . That being said we are running tests to ensure DevLess runs smoothly on PHP 7 before porting. To resolve your issue kindly install with 5.6 or even better you can install with Docker https://devless.gitbooks.io/devless-docs-1-3-0/dev-setup.html

**Comment by EDDYMENS** [comment]
also don't forget to star the project @mhsenpc  :)
