### ISSUE TITLE
Strange behaviour at Users Management and Error when cancel update User

### ISSUE THREAD

**Issue by roylisto** [DevlessTeam/DV-PHP-CORE#95]
This is how to reproduce it

**Problem 1:**

1. Open the Users Management

![image](https://user-images.githubusercontent.com/33563774/39957260-ae1ff00c-5622-11e8-9424-7e9e9c31bee5.png)

2. Select user with empty username
![image](https://user-images.githubusercontent.com/33563774/39957224-02246b70-5622-11e8-8303-8a765ba91497.png)

3. Click cancel & I got this error

![image](https://user-images.githubusercontent.com/33563774/39957229-1afe20dc-5622-11e8-9f54-ec4eb5a3de29.png)

**Problem 2:**

1. Open the Users Management

![image](https://user-images.githubusercontent.com/33563774/39957260-ae1ff00c-5622-11e8-9424-7e9e9c31bee5.png)

2.  Select last user in grid

![image](https://user-images.githubusercontent.com/33563774/39957244-53d20eb4-5622-11e8-89d9-78efa4b3d08d.png)

3. Click cancel , and the last grid will copied to first grid

![image](https://user-images.githubusercontent.com/33563774/39957250-6c573bee-5622-11e8-969f-1c017c334aba.png)

note: this problem is happening when deleting and updating user too

**Comment by paynegreen** [comment]
@tokanggit thank you for pointing out the issue. 👍 It has been fixed and will be released soon.
